spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://localhost:3306/blogpark?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123

# mybatis 配置内容
mybatis:
  config-location: classpath:db/mybatis-config.xml # 配置 MyBatis 配置文件路径
#  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.kongmu373.park.entity # 配置数据库实体包路径

