spring:
  # datasource \u6570\u636E\u6E90\u914D\u7F6E\u5185\u5BB9
  datasource:
    # \u66FF\u6362\u81EA\u5DF1\u7684ip(\u5982:192.168.77.1)
    url: jdbc:mysql://192.168.77.1:3306/blogpark?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123